### ISSUE TITLE
KeyComposta Memcached

### ISSUE THREAD

**Issue by Srlimao** [selatotal/SistemasDistribuidos#1]
Quando montando a chave com um nome composto ex.: 'Neymar Jr' como devo criar a chave?
SD_Data_2015_Neymar+Jr ou SD_Data_2015_Neymar_Jr ou SD_Data_2015_NeymarJr

**Comment by selatotal** [comment]
Meio atrasado, mas... 
SD_Data_2015_Neymar+Jr
